name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on PR to any branch

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    env:
      COGNITO_USER_POOL_ID: mock-user-pool-id
      COGNITO_APP_CLIENT_ID: mock-client-id
      COGNITO_APP_CLIENT_SECRET: mock-client-secret
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: mock-access-key
      AWS_SECRET_ACCESS_KEY: mock-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Log cache key
        run: echo "Cache key: $RUNNER_OS-pip-$(hashFiles '**/requirements*.txt')"

      - name: Debug pip cache path
        run: ls -lah ~/.cache/pip || echo "No cache restored"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt -r src/backend/requirements-dev.txt

      - name: Run unit tests
        run: pytest test --cov=src --cov-report=term --cov-report=xml

      - name: Run Flake8
        run: flake8 src test

      - name: Run MyPy
        run: mypy src test

  # build-and-push:
  #   needs: test-and-lint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push backend Docker image
  #       run: |
  #         docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./src/backend
  #         docker push ghcr.io/${{ github.repository_owner }}/backend:latest
